import type {
  Appointment,
  Artist,
  Client,
  ConsentForm,
  Payment,
  PortfolioItem,
  Studio,
  TattooAuction,
  VerifiedUser,
} from "./types";

export const studio: Studio = {
  id: "studio-1",
  name: "Enderson Carrizo",
  slug: "enderson-carrizo",
  tagline: "Tatuajes artísticos en Santiago, Chile.",
  city: "Santiago",
  address: "Santiago, Chile",
  phone: "+56 9 9181 3566",
  instagram: "@carrizoartist",
  tiktok: "@carrizoartist",
  tiktokUrl: "https://www.tiktok.com/@carrizoartist",
  facebook:
    "https://www.facebook.com/people/Enderxon-Carrizo/100049090131552/",
  bio: "Artista de tatuajes artísticos. Cada pieza nace de una idea personal y se traduce en una intervención corporal con detalle, intención y acabado profesional.",
  avatarUrl: "/artists/enderson/logo-dark.png",
  logoUrl: "/artists/enderson/logo-dark.png",
  coverUrl: "/artists/enderson/cover.jpg",
  followersLabel: "744 seguidores en Facebook",
  depositPercent: 30,
  aftercareText:
    "Mantén el vendaje 2-4 horas. Lava con jabón neutro, aplica crema fina 2-3 veces al día. Evita sol, piscina y ejercicio intenso 10-14 días.",
};

export const artists: Artist[] = [
  {
    id: "artist-1",
    name: "Enderson Carrizo",
    slug: "enderson",
    role: "Artista · Tatuajes artísticos",
    bio: "Tatuador en Santiago especializado en piezas artísticas y personalizadas. Trabajo por agenda, con abono para confirmar sesión y seguimiento profesional del proceso.",
    specialties: ["realismo", "blackwork", "fine_line", "tradicional", "otro"],
    avatar: "EC",
    photoUrl: "/artists/enderson/logo-dark.png",
    hourlyRate: 65000,
    commissionPercent: 100,
    active: true,
  },
];

export const clients: Client[] = [
  {
    id: "client-1",
    name: "Camila Vargas",
    email: "camila@email.com",
    phone: "+56 9 4000 1111",
    allergies: "Ninguna",
    notes: "Prefiere sesiones de mañana",
    totalSpent: 280000,
    visits: 3,
    createdAt: "2025-11-12T10:00:00.000Z",
    lastVisit: "2026-06-20T14:00:00.000Z",
  },
  {
    id: "client-2",
    name: "Martín López",
    email: "martin@email.com",
    phone: "+56 9 4000 2222",
    allergies: "Látex",
    notes: "Manga en progreso — brazo derecho",
    totalSpent: 520000,
    visits: 5,
    createdAt: "2025-08-03T10:00:00.000Z",
    lastVisit: "2026-06-28T11:00:00.000Z",
  },
  {
    id: "client-3",
    name: "Sofía Méndez",
    email: "sofia@email.com",
    phone: "+56 9 4000 3333",
    allergies: "Ninguna",
    notes: "Primera vez",
    totalSpent: 0,
    visits: 0,
    createdAt: "2026-07-01T09:00:00.000Z",
  },
  {
    id: "client-4",
    name: "Diego Fernández",
    email: "diego@email.com",
    phone: "+56 9 4000 4444",
    allergies: "Ninguna",
    notes: "Cliente recurrente",
    totalSpent: 190000,
    visits: 2,
    createdAt: "2026-01-15T10:00:00.000Z",
    lastVisit: "2026-05-10T16:00:00.000Z",
  },
  {
    id: "client-5",
    name: "Ana Torres",
    email: "ana@email.com",
    phone: "+56 9 4000 5555",
    allergies: "Sensibilidad a tintas rojas",
    notes: "Usar solo negro y gris",
    totalSpent: 95000,
    visits: 1,
    createdAt: "2026-04-02T10:00:00.000Z",
    lastVisit: "2026-04-18T13:00:00.000Z",
  },
];

const today = new Date();
const at = (daysFromNow: number, hour: number, durationHours = 3) => {
  const start = new Date(today);
  start.setDate(start.getDate() + daysFromNow);
  start.setHours(hour, 0, 0, 0);
  const end = new Date(start);
  end.setHours(start.getHours() + durationHours);
  return { startAt: start.toISOString(), endAt: end.toISOString() };
};

export const appointments: Appointment[] = [
  {
    id: "apt-1",
    clientId: "client-1",
    artistId: "artist-1",
    title: "Pieza artística — espalda",
    style: "realismo",
    zone: "espalda",
    size: "grande",
    description: "Intervención corporal de gran formato, detalle y composición personalizada",
    references: [],
    status: "confirmado",
    ...at(0, 14, 4),
    estimatedHours: 4,
    quotedPrice: 320000,
    depositAmount: 96000,
    depositPaid: true,
    balancePaid: false,
    consentSigned: true,
    consentId: "consent-1",
    budget: 350000,
    createdAt: "2026-06-15T10:00:00.000Z",
  },
  {
    id: "apt-2",
    clientId: "client-2",
    artistId: "artist-1",
    title: "Manga — sesión de avance",
    style: "blackwork",
    zone: "brazo",
    size: "manga",
    description: "Continuación de manga artística",
    references: [],
    status: "confirmado",
    ...at(0, 10, 3),
    estimatedHours: 3,
    quotedPrice: 210000,
    depositAmount: 63000,
    depositPaid: true,
    balancePaid: false,
    consentSigned: true,
    consentId: "consent-2",
    createdAt: "2026-06-10T10:00:00.000Z",
  },
  {
    id: "apt-3",
    clientId: "client-3",
    artistId: "artist-1",
    title: "Fine line — muñeca",
    style: "fine_line",
    zone: "muñeca",
    size: "pequeño",
    description: "Diseño minimalista personalizado",
    references: [],
    status: "solicitud",
    ...at(2, 11, 2),
    estimatedHours: 1.5,
    quotedPrice: 95000,
    depositAmount: 29000,
    depositPaid: false,
    balancePaid: false,
    consentSigned: false,
    budget: 100000,
    createdAt: "2026-07-01T09:30:00.000Z",
  },
  {
    id: "apt-4",
    clientId: "client-4",
    artistId: "artist-1",
    title: "Pieza antebrazo",
    style: "tradicional",
    zone: "antebrazo",
    size: "mediano",
    description: "Diseño artístico a color",
    references: [],
    status: "seña_pendiente",
    ...at(3, 15, 3),
    estimatedHours: 3,
    quotedPrice: 195000,
    depositAmount: 59000,
    depositPaid: false,
    balancePaid: false,
    consentSigned: false,
    budget: 200000,
    createdAt: "2026-06-28T12:00:00.000Z",
  },
  {
    id: "apt-5",
    clientId: "client-5",
    artistId: "artist-1",
    title: "Lettering — costillas",
    style: "lettering",
    zone: "costillas",
    size: "mediano",
    description: "Frase en tipografía elegante",
    references: [],
    status: "cotizado",
    ...at(5, 12, 2),
    estimatedHours: 2.5,
    quotedPrice: 160000,
    depositAmount: 48000,
    depositPaid: false,
    balancePaid: false,
    consentSigned: false,
    budget: 150000,
    createdAt: "2026-06-30T16:00:00.000Z",
  },
  {
    id: "apt-6",
    clientId: "client-1",
    artistId: "artist-1",
    title: "Pieza hombro",
    style: "otro",
    zone: "hombro",
    size: "pequeño",
    description: "Trabajo artístico cerrado",
    references: [],
    status: "completado",
    ...at(-5, 16, 2),
    estimatedHours: 2,
    quotedPrice: 120000,
    depositAmount: 36000,
    depositPaid: true,
    balancePaid: true,
    consentSigned: true,
    consentId: "consent-3",
    createdAt: "2026-06-20T10:00:00.000Z",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-1",
    appointmentId: "apt-1",
    clientId: "client-1",
    artistId: "artist-1",
    type: "seña",
    amount: 96000,
    method: "mercadopago",
    createdAt: "2026-06-16T10:00:00.000Z",
  },
  {
    id: "pay-2",
    appointmentId: "apt-2",
    clientId: "client-2",
    artistId: "artist-1",
    type: "seña",
    amount: 63000,
    method: "transferencia",
    createdAt: "2026-06-11T10:00:00.000Z",
  },
  {
    id: "pay-3",
    appointmentId: "apt-6",
    clientId: "client-1",
    artistId: "artist-1",
    type: "seña",
    amount: 36000,
    method: "efectivo",
    createdAt: "2026-06-18T10:00:00.000Z",
  },
  {
    id: "pay-4",
    appointmentId: "apt-6",
    clientId: "client-1",
    artistId: "artist-1",
    type: "saldo",
    amount: 84000,
    method: "efectivo",
    createdAt: "2026-06-28T18:00:00.000Z",
  },
  {
    id: "pay-5",
    appointmentId: "apt-6",
    clientId: "client-1",
    artistId: "artist-1",
    type: "propina",
    amount: 15000,
    method: "efectivo",
    createdAt: "2026-06-28T18:05:00.000Z",
  },
];

export const portfolio: PortfolioItem[] = [
  {
    id: "port-1",
    artistId: "artist-1",
    title: "Intervención corporal",
    style: "realismo",
    image: "/artists/enderson/work-1.jpg",
    featured: true,
  },
  {
    id: "port-2",
    artistId: "artist-1",
    title: "Detalle artístico",
    style: "blackwork",
    image: "/artists/enderson/work-2.jpg",
    featured: true,
  },
  {
    id: "port-3",
    artistId: "artist-1",
    title: "Composición personalizada",
    style: "fine_line",
    image: "/artists/enderson/work-3.jpg",
    featured: true,
  },
  {
    id: "port-4",
    artistId: "artist-1",
    title: "Pieza de estudio",
    style: "tradicional",
    image: "/artists/enderson/work-4.jpg",
    featured: true,
  },
  {
    id: "port-5",
    artistId: "artist-1",
    title: "Trabajo reciente",
    style: "otro",
    image: "/artists/enderson/work-5.jpg",
    featured: true,
  },
  {
    id: "port-6",
    artistId: "artist-1",
    title: "Portada de perfil",
    style: "otro",
    image: "/artists/enderson/cover.jpg",
    featured: false,
  },
];

export const consents: ConsentForm[] = [
  {
    id: "consent-1",
    appointmentId: "apt-1",
    clientId: "client-1",
    clientName: "Camila Vargas",
    signedAt: "2026-06-20T13:50:00.000Z",
    signatureData: "Camila Vargas",
    acceptedTerms: true,
    healthDeclaration: "Sin condiciones relevantes",
  },
  {
    id: "consent-2",
    appointmentId: "apt-2",
    clientId: "client-2",
    clientName: "Martín López",
    signedAt: "2026-06-28T10:45:00.000Z",
    signatureData: "Martín López",
    acceptedTerms: true,
    healthDeclaration: "Alergia a látex — usar guantes de nitrilo",
  },
  {
    id: "consent-3",
    appointmentId: "apt-6",
    clientId: "client-1",
    clientName: "Camila Vargas",
    signedAt: "2026-06-28T15:50:00.000Z",
    signatureData: "Camila Vargas",
    acceptedTerms: true,
    healthDeclaration: "Sin condiciones relevantes",
  },
];

const auctionStart = new Date(Date.now() - 5 * 60 * 1000);
const auctionEnd = new Date(Date.now() + 25 * 60 * 1000);

export const verifiedUsers: VerifiedUser[] = [
  {
    id: "user-verified-1",
    name: "Sofía Méndez",
    email: "sofia@email.com",
    phone: "+56 9 4000 3333",
    rut: "12.345.678-9",
    documentType: "cedula",
    documentFileName: "cedula-sofia.jpg",
    profilePhotoUrl: "/artists/enderson/avatar.jpg",
    documentDataUrl: "/artists/enderson/avatar.jpg",
    passwordHash:
      "pbkdf2-sha256:600000:E0MasYhP/SkAwYKoYiSF9Q==:HoZ9r1OjLKaMbfVmw/+MnQYYUWafqnPqUd7Yi9n4v0c=",
    verificationStatus: "verificado",
    submittedAt: "2026-06-20T10:00:00.000Z",
    reviewedAt: "2026-06-20T12:00:00.000Z",
    reviewedBy: "Equipo Inkora",
    createdAt: "2026-06-19T10:00:00.000Z",
  },
  {
    id: "user-review-1",
    name: "Diego Fernández",
    email: "diego@email.com",
    phone: "+56 9 4000 4444",
    rut: "16.111.222-3",
    documentType: "cedula",
    documentFileName: "cedula-diego.jpg",
    documentDataUrl: "/artists/enderson/cover.jpg",
    passwordHash:
      "pbkdf2-sha256:600000:v5NeVUHp23zoa8SJc3NDxg==:bjvLu/89CZsWwtlhJUxfoWALSnud1717DXrCMwV3NMg=",
    verificationStatus: "en_revision",
    submittedAt: "2026-07-03T15:00:00.000Z",
    createdAt: "2026-07-03T14:50:00.000Z",
  },
  {
    id: "user-pending-1",
    name: "Ana Torres",
    email: "ana@email.com",
    phone: "+56 9 4000 5555",
    rut: "18.222.333-4",
    documentType: "pasaporte",
    passwordHash:
      "pbkdf2-sha256:600000:A9CFt8z7IOfDrbOUinawMQ==:TtwDegQmqnHUBspT46iJ9toRZzTq2gzYt2fNz+Sxe9M=",
    verificationStatus: "pendiente_documento",
    createdAt: "2026-07-03T16:00:00.000Z",
  },
];

export const auctions: TattooAuction[] = [
  {
    id: "auction-live-1",
    artistId: "artist-1",
    title: "Flash exclusivo de la noche",
    description:
      "Diseño artístico único de Enderson Carrizo. El mejor postor se lleva la pieza y agenda la sesión con abono incluido en el valor final.",
    style: "blackwork",
    size: "mediano",
    image: "/artists/enderson/work-1.jpg",
    startingPrice: 80000,
    minIncrement: 5000,
    currentBid: 95000,
    status: "en_vivo",
    startsAt: auctionStart.toISOString(),
    endsAt: auctionEnd.toISOString(),
    viewers: 18,
    createdAt: auctionStart.toISOString(),
    bids: [
      {
        id: "bid-3",
        auctionId: "auction-live-1",
        bidderName: "Sofía Méndez",
        bidderPhone: "+56 9 4000 3333",
        bidderUserId: "user-verified-1",
        verificationStatus: "verificado",
        amount: 95000,
        createdAt: new Date(Date.now() - 90 * 1000).toISOString(),
      },
      {
        id: "bid-2",
        auctionId: "auction-live-1",
        bidderName: "Diego Fernández",
        bidderPhone: "+56 9 4000 4444",
        bidderUserId: "user-review-1",
        verificationStatus: "en_revision",
        amount: 85000,
        createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      },
      {
        id: "bid-1",
        auctionId: "auction-live-1",
        bidderName: "Camila Vargas",
        bidderPhone: "+56 9 4000 1111",
        verificationStatus: "verificado",
        amount: 80000,
        createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      },
    ],
  },
];
